[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pdfanonymizer"
version = "0.1.0"
description = "A PDF anonymizer library"
authors = [{name="Glauco Siliprandi", email="your.email@example.com"}]
dependencies = ["PyPDF2>=3.0"]
